/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author banor
 */
public class ExistingAccountFrame extends javax.swing.JFrame {

    Bank bankModel;

    /**
     * Creates new form ExistingAccountFrame
     */
    public ExistingAccountFrame(Bank bankModel) {
        this.bankModel = bankModel;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        selectOptionLabel = new javax.swing.JLabel();
        accountNumberField = new javax.swing.JTextField();
        optionsComboBox = new javax.swing.JComboBox<>();
        enterAccountNumberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(51, 153, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Niner Bank");

        selectOptionLabel.setText("Select an option");

        accountNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberFieldActionPerformed(evt);
            }
        });

        optionsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Close account", "Deposit", "Withdraw", "Display account" }));

        enterAccountNumberLabel.setText("Enter account number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectOptionLabel)
                                    .addComponent(enterAccountNumberLabel))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(optionsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(accountNumberField))
                                .addGap(80, 80, 80))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterAccountNumberLabel)
                    .addComponent(accountNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectOptionLabel)
                    .addComponent(optionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(submitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumberFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        int accNumber = Integer.parseInt(accountNumberField.getText());
        String option = optionsComboBox.getSelectedItem().toString();
        switch (option) {
            case "Close account":
                boolean closed = bankModel.closeAccount(accNumber);
                if (closed) {
                    String message = "The account was successfuly closed.";
                    JOptionPane.showMessageDialog(new JFrame(), message, "Account Closed", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String message = "The account was not found.";
                    JOptionPane.showMessageDialog(new JFrame(), message, "Account Not Found", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            case "Deposit":
                double depositAmount = Double.parseDouble(JOptionPane.showInputDialog(new JFrame(), "Amount?"));
                boolean deposited = bankModel.depositAccount(accNumber, depositAmount);
                if (deposited) {
                    String message = "The deposit was successful.";
                    JOptionPane.showMessageDialog(new JFrame(), message, "Deposit Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String message = "Account could not be found.";
                    JOptionPane.showMessageDialog(new JFrame(), message, "Account Not Found", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            case "Withdraw":
                double withdrawAmount = Double.parseDouble(JOptionPane.showInputDialog(new JFrame(), "Amount?"));
                boolean withdrawn = bankModel.withdrawAccount(accNumber, withdrawAmount);
                if (withdrawn) {
                    String message = "The withdraw was successful.";
                    JOptionPane.showMessageDialog(new JFrame(), message, "Withdraw Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String message = "Account could not be found.";
                    JOptionPane.showMessageDialog(new JFrame(), message, "Account Not Found", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            case "Display account":
                String info = bankModel.toStringAccount(accNumber);
                if (info != null) {
                    JOptionPane.showMessageDialog(new JFrame(), info, "Account Information", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String message = "Account not found.";
                    JOptionPane.showMessageDialog(new JFrame(), message, "Account Not Found", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        StartFrame startFrame = new StartFrame(bankModel);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumberField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel enterAccountNumberLabel;
    private javax.swing.JComboBox<String> optionsComboBox;
    private javax.swing.JLabel selectOptionLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
