package nortonbrandontest3;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author banor
 */
public class StartFrame extends javax.swing.JFrame {

    PhoneBook phoneBook;

    /**
     * Creates new form StartFrame
     *
     * @param phoneBook
     */
    public StartFrame(PhoneBook phoneBook) {
        this.phoneBook = phoneBook;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        addDeleteButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        updateNumButton = new javax.swing.JButton();
        allEntriesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Phone Book");

        addDeleteButton.setText("Add/Delete Entry");
        addDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeleteButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search Entry");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        updateNumButton.setText("Update Phone Number");
        updateNumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateNumButtonActionPerformed(evt);
            }
        });

        allEntriesButton.setText("All Entries");
        allEntriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allEntriesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(allEntriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateNumButton)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(addDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDeleteButton)
                    .addComponent(searchButton))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allEntriesButton)
                    .addComponent(updateNumButton))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeleteButtonActionPerformed
        this.dispose();
        AddDeleteFrame addDeleteFrame = new AddDeleteFrame(this.phoneBook);
    }//GEN-LAST:event_addDeleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        this.dispose();
        SearchFrame searchFrame = new SearchFrame(this.phoneBook);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateNumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateNumButtonActionPerformed
        this.dispose();
        UpdateNumberFrame updateNumberFrame = new UpdateNumberFrame(this.phoneBook);
    }//GEN-LAST:event_updateNumButtonActionPerformed

    private void allEntriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allEntriesButtonActionPerformed
        JOptionPane.showMessageDialog(null, phoneBook.displayAll());
        this.dispose();
        StartFrame startFrame = new StartFrame(this.phoneBook);
    }//GEN-LAST:event_allEntriesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeleteButton;
    private javax.swing.JButton allEntriesButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateNumButton;
    // End of variables declaration//GEN-END:variables
}
