/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7storybook;

import java.util.Random;

/**
 *
 * @author banor
 */
public class EndFrame extends javax.swing.JFrame {
    StorybookModel myModel = new StorybookModel();
    Random rand = new Random();
    int randNum = rand.nextInt(2);
    /**
     * Creates new form EndFrame
     */
    public EndFrame(StorybookModel model) {
        initComponents();
        this.myModel = model;
        welcomeLabel.setText("Welcome, " + myModel.getUsername() + ".");
        crimeLabel.setText("You have been accused of " + myModel.getCrime() + "!");
        instructionLabel.setText("Pick a door to determine your verdict");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        crimeLabel = new javax.swing.JLabel();
        instructionLabel = new javax.swing.JLabel();
        leftDoorButton = new javax.swing.JButton();
        rightDoorButton = new javax.swing.JButton();
        exitTribunalButton = new javax.swing.JButton();
        nextTrialButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("Welcome");

        crimeLabel.setText("Crime");

        instructionLabel.setText("Instruction");

        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Door.GIF"))); // NOI18N
        leftDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorButtonActionPerformed(evt);
            }
        });

        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Door.GIF"))); // NOI18N
        rightDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorButtonActionPerformed(evt);
            }
        });

        exitTribunalButton.setText("Exit Tribunal");
        exitTribunalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitTribunalButtonActionPerformed(evt);
            }
        });

        nextTrialButton.setText("Next Trial -->");
        nextTrialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTrialButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(crimeLabel)
                    .addComponent(instructionLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftDoorButton)
                    .addComponent(exitTribunalButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightDoorButton)
                    .addComponent(nextTrialButton))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rightDoorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instructionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(leftDoorButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitTribunalButton)
                    .addComponent(nextTrialButton))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorButtonActionPerformed
        if (randNum == 1){
        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Tiger.GIF")));
        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Lady.GIF")));
        instructionLabel.setText("You are GUILTY! Prepare to be eaten!");
        }
        if (randNum == 0){
        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Lady.GIF")));
        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Tiger.GIF")));
        instructionLabel.setText("You are INNOCENT! Sorry about that. Please accept this lady.");
        }
        rightDoorButton.setEnabled(false);
        nextTrialButton.setEnabled(true);
        exitTribunalButton.setEnabled(true);
    }//GEN-LAST:event_leftDoorButtonActionPerformed

    private void rightDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorButtonActionPerformed
        if (randNum == 1){
        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Tiger.GIF")));
        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Lady.GIF")));
        instructionLabel.setText("You are INNOCENT! Sorry about that. Please accept this lady.");  
        }
        if (randNum == 0){
        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Lady.GIF")));
        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7storybook/Tiger.GIF")));
        instructionLabel.setText("You are GUILTY! Prepare to be eaten!");
        }
        leftDoorButton.setEnabled(false);
        nextTrialButton.setEnabled(true);
        exitTribunalButton.setEnabled(true);
    }//GEN-LAST:event_rightDoorButtonActionPerformed

    private void exitTribunalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitTribunalButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitTribunalButtonActionPerformed

    private void nextTrialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTrialButtonActionPerformed
        StartFrame myStartFrame = new StartFrame(myModel);
        myStartFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextTrialButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crimeLabel;
    private javax.swing.JButton exitTribunalButton;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JButton leftDoorButton;
    private javax.swing.JButton nextTrialButton;
    private javax.swing.JButton rightDoorButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
